# Generated by Django 4.0.3 on 2022-04-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='avatar_url',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='first_name',
            field=models.CharField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='gender',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='last_name',
            field=models.CharField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.CharField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='roomstatus',
            name='status',
            field=models.CharField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_type',
            field=models.CharField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(default=None, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=None, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
